[build-system]
requires = ["hatchling",
  "the-caddie",
  "uv-dynamic-versioning"]
build-backend = "hatchling.build"

[project]
name = "common_access_model"
description = "Internal Access model for the INCLUDE DCC."
authors = [
  {name = "Robert Carroll", email = "robert.carroll@vumc.org"},
]
license = "MIT"
license-files = ["LICENSE"]
readme = "README.md"
requires-python = ">=3.10,<3.14"
dynamic = ["version"]

dependencies = [
  "hatchling>=1.32.0",
  "linkml>=1.11.0",
  "linkml-runtime>=1.11.0",
  "the-caddie",
]

[dependency-groups]
dev = [
    "linkml>=1.9.3",
    "mkdocs-material>=8.2.8",
    "mkdocs-mermaid2-plugin>=1.1.1",
    "jupyter>=1.0.0",
    "mknotebooks>= 0.8.0",
    "hatchling>=1.27.0",
    "tomli>=2.0.0",
    "the-caddie",
]

# See https://hatch.pypa.io/latest/config/build/#file-selection for how to
# explicitly include files other than default into the build distributions.

[tool.hatch.version]
source = "uv-dynamic-versioning"

# Ref.: https://github.com/ninoseki/uv-dynamic-versioning/
[tool.uv-dynamic-versioning]
vcs = "git"
style = "pep440"
pattern = "^v?(?P<base>\\d+\\.\\d+\\.\\d+)"
fallback-version = "0.0.0"

[tool.hatch.build.targets.sdist]
exclude = [
  ".direnv",
  ".venv",
  "scratch"
]
include = [
  "src/common_access_model/schema/",
  "project/sqlalchemy/",
  "scripts/",
]

# Activate the hook
[tool.hatch.build.targets.wheel.hooks.caddie-sqla]


# Ref.: https://docs.pytest.org/en/stable/reference/reference.html#configuration-options
[tool.pytest.ini_options]
testpaths = ["tests"]

# Ref.: https://github.com/codespell-project/codespell
[tool.codespell]
skip = [
  "LICENSE",
  "pyproject.toml",
  "uv.lock",
  "project/*",
  "src/common_access_model/datamodel/common_access_model_pydantic.py",
  "src/common_access_model/datamodel/common_access_model.py",
]

# Reminder: words have to be lowercased for the ignore-words-list
ignore-words-list = "linke"
quiet-level = 3

# Ref.: https://github.com/crate-ci/typos (spell checker)
[tool.typos.default.extend-words]
linke = "linke"
[tool.typos.files]
extend-exclude = [
  "LICENSE",
  "uv.lock",
  "pyproject.toml",
  "project/*",
  "src/common_access_model/datamodel/common_access_model_pydantic.py",
  "src/common_access_model/datamodel/common_access_model.py",
]


[tool.uv.sources]
the-caddie = { git = "https://github.com/carrollaboratory/the-caddie" }
